const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
let state=null,selected=null,layer='ownership',refreshTimer=null;
let viewerDid=localStorage.getItem('flopEmpiresViewerDid')||'';
let view={x:0,y:0,w:900,h:900},drag=null;
const fmt=n=>new Intl.NumberFormat('en-US').format(Number(n||0));
const time=t=>new Date(Number(t)*1000).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function canonical(obj){const sort=x=>Array.isArray(x)?x.map(sort):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,sort(x[k])])):x;return JSON.stringify(sort(obj))}
function membership(){if(!state||!viewerDid)return null;return state.registration.memberships.find(m=>m.actor_did===viewerDid)||null}
function myEmpire(){const m=membership();return m?state.world.empires.find(e=>e.id===m.empire_id):null}
async function load(){try{const r=await fetch('/api/state',{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);state=await r.json();render()}catch(e){$('#statusText').textContent='UI offline';console.error(e)}}
function render(){renderHeader();renderStats();renderMap();renderEmpires();renderWar();renderActivity();renderRules();renderIdentity();if(selected)renderTerritory(selected)}
function renderHeader(){const s=state.season;$('#statusText').textContent=s.status;$('#statusDot').classList.toggle('live',['REGISTRATION','ACTIVE'].includes(s.status));let label='';if(s.status==='REGISTRATION')label=` · starts ${time(s.season_start)}`;else if(s.status==='ACTIVE')label=` · ends ${time(s.season_end)}`;$('#countdown').textContent=label;document.title=`FLOP Empires · ${s.status}`;$('#identityButton').textContent=myEmpire()?myEmpire().name:viewerDid?'Identity set':'Identity'}
function renderStats(){const s=state,w=state.world,a=state.activity,claimed=w.empires.filter(e=>e.claimed).length;const cards=[['Phase',s.status,`Season 0 · ${time(s.season_start)}`],['Registered',state.registration.actors,`${claimed}/16 empire slots claimed`],['World','64 territories',w.live_materialized?'Live materialized':'Frozen baseline'],['Open attacks',a.active_attacks.length,`${a.active_alliances.length} active alliances`]];$('#heroStats').innerHTML=cards.map(([k,v,x])=>`<div class="stat"><span>${esc(k)}</span><strong>${esc(v)}</strong><small>${esc(x)}</small></div>`).join('')}
function regionMarkup(){const groups={};for(const t of state.world.territories)(groups[t.region]??=[]).push(t);return Object.entries(groups).map(([name,items])=>{const cx=items.reduce((a,t)=>a+t.x,0)/items.length,cy=items.reduce((a,t)=>a+t.y,0)/items.length;return `<g class="region"><circle class="region-zone" cx="${cx}" cy="${cy}" r="105"/><text class="region-label" x="${cx}" y="${cy+118}">${name.toUpperCase()}</text></g>`}).join('')}
function renderMap(){const svg=$('#worldMap'),viewport=$('#viewport'),byId=Object.fromEntries(state.world.territories.map(t=>[t.id,t]));const mine=myEmpire()?.id||null;const conflict=new Set(state.activity.active_attacks.flatMap(a=>[a.origin_id,a.target_id]));let out=regionMarkup();for(const [a,b] of state.world.edges){const A=byId[a],B=byId[b];if(A&&B)out+=`<line class="edge" x1="${A.x}" y1="${A.y}" x2="${B.x}" y2="${B.y}"/>`}
for(const atk of state.activity.active_attacks){const A=byId[atk.origin_id],B=byId[atk.target_id];if(A&&B)out+=`<line class="attack-line" x1="${A.x}" y1="${A.y}" x2="${B.x}" y2="${B.y}"/>`}
for(const t of state.world.territories){const classes=['territory',t.capital?'capital':'',t.strategic_value>1?'strategic':'',mine&&t.owner===mine?'mine':'enemy',conflict.has(t.id)?'in-conflict':'',selected===t.id?'selected':''].filter(Boolean).join(' ');const r=t.capital?17:t.strategic_value>1?14:11;out+=`<g class="${classes}" data-id="${t.id}" tabindex="0" role="button" aria-label="${esc(t.id)} owned by ${esc(t.owner_name)}"><circle class="node" cx="${t.x}" cy="${t.y}" r="${r}" fill="${t.color}"/>${t.capital?`<circle class="ring" cx="${t.x}" cy="${t.y}" r="${r+6}"/>`:''}${t.strategic_value>1?`<text x="${t.x}" y="${t.y}">✦</text>`:''}</g>`}
viewport.innerHTML=out;svg.setAttribute('viewBox',`${view.x} ${view.y} ${view.w} ${view.h}`);const card=$('.map-card');card.classList.remove('layer-regions','layer-strategic','layer-conflict');if(layer!=='ownership')card.classList.add(`layer-${layer}`);$$('.territory',viewport).forEach(el=>{const pick=()=>{selected=el.dataset.id;renderMap();renderTerritory(selected)};el.addEventListener('click',pick);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick()}})});$('#worldNotice').textContent=state.world.live_materialized?'Live canonical world · public fog-safe projection.':'Frozen baseline · world rows not materialized.'}
function neighbors(id){const n=[];for(const [a,b] of state.world.edges){if(a===id)n.push(b);else if(b===id)n.push(a)}return n.sort()}
function renderTerritory(id){const t=state.world.territories.find(x=>x.id===id);if(!t)return;const mine=myEmpire()?.id||null,owned=mine&&t.owner===mine,atk=state.activity.active_attacks.find(a=>a.target_id===id||a.origin_id===id);const badge=owned?'<span class="my-badge">MY TERRITORY</span>':'';$('#territoryDetail').innerHTML=`<div class="detail-title"><div><span class="eyebrow">${esc(t.region.toUpperCase())}</span><h2>${esc(t.id)}${badge}</h2></div><span>${t.capital?'◆ CAPITAL':t.strategic_value>1?'✦ STRATEGIC':''}</span></div><div class="owner-pill"><i style="background:${t.color}"></i>${esc(t.owner_name)}</div><div class="kv"><div><span>Strategic value</span><strong>${fmt(t.strategic_value)}</strong></div><div><span>Fortification</span><strong>Hidden by fog</strong></div><div><span>Production</span><strong>Hidden by fog</strong></div><div><span>State</span><strong>${t.live?'Canonical live':'Frozen baseline'}</strong></div></div><div class="neighbors">${neighbors(id).map(n=>`<button class="chip" data-neighbor="${n}">${n}</button>`).join('')}</div>${atk?`<div class="world-notice">Open ${esc(atk.kind)} · deadline ${time(atk.deadline_at)}</div>`:''}<div class="detail-actions"><button class="action-btn" data-action="recon">Recon</button>${owned?'<button class="action-btn" data-action="fortify">Fortify</button>':'<button class="action-btn" data-action="raid">Raid</button><button class="action-btn" data-action="siege">Siege</button>'}</div><div class="privacy-note">Public UI never reveals private defense or production values. A signed viewer session is required before any future private projection can do so safely.</div>`;$$('[data-neighbor]').forEach(b=>b.onclick=()=>{selected=b.dataset.neighbor;renderMap();renderTerritory(selected)});$$('[data-action]').forEach(b=>b.onclick=()=>openAction(b.dataset.action,t))}
function renderEmpires(){const mine=myEmpire()?.id||null,sorted=[...state.world.empires].sort((a,b)=>Number(b.claimed)-Number(a.claimed)||a.id.localeCompare(b.id));$('#empireGrid').innerHTML=sorted.map(e=>`<article class="empire-card ${e.claimed?'':'unclaimed'}"><header><h3>${esc(e.name)}${e.id===mine?'<span class="my-badge">MINE</span>':''}</h3><span class="swatch" style="background:${e.color}"></span></header><div class="power">${esc(e.standing||'Unranked')}</div><small class="muted">${e.claimed?`${e.members} member${e.members===1?'':'s'}`:'open Season 0 slot'}</small><div class="resource-row"><div><small>PRESTIGE</small><strong>${fmt(e.prestige_public)}</strong></div><div><small>FOG</small><strong>ON</strong></div><div><small>SLOT</small><strong>${e.claimed?'CLAIMED':'OPEN'}</strong></div></div>${!e.claimed&&state.season.status==='REGISTRATION'?`<button class="action-btn claim-inline" data-claim="${e.id}">Build join command</button>`:''}</article>`).join('');$$('[data-claim]').forEach(b=>b.onclick=()=>openJoin(b.dataset.claim))}
function renderWar(){const list=state.activity.active_attacks;if(!list.length){$('#warList').innerHTML='<div class="empty-state">No open Raid or Siege windows.</div>';return}$('#warList').innerHTML=list.map(a=>`<article class="list-item"><div class="event-icon">${a.kind==='SIEGE'?'S':'R'}</div><div><strong>${esc(a.attacker_empire_id)} → ${esc(a.defender_empire_id)}</strong><small>${esc(a.origin_id)} → ${esc(a.target_id)} · committed force hidden by fog</small></div><time>${time(a.deadline_at)}</time></article>`).join('')}
function renderActivity(){const list=state.activity.recent_events;if(!list.length){$('#activityList').innerHTML='<div class="empty-state">No canonical game events yet.</div>';return}$('#activityList').innerHTML=list.map(e=>`<article class="list-item"><div class="event-icon">${e.accepted?'✓':'×'}</div><div><strong>${esc(e.event_type)}</strong><small>${esc(e.request_id)} · event #${fmt(e.seq)}</small></div><time>${time(e.accepted_at)}</time></article>`).join('')}
function renderRules(){const c=state.capabilities||{},e=state.evidence||{};const caps=[['Fog-safe public projection',c.fog_safe_public_projection],['Viewer highlight',c.viewer_highlight_without_private_reveal],['Signed private view',c.signed_private_view],['Raid / Siege',c.raid_siege],['Recon',c.recon],['Alliances runtime',c.alliances_runtime],['Treaties runtime',c.treaties_runtime_materialized],['Trade runtime',c.trade_runtime_materialized],['Standing runtime',c.standing_runtime_materialized]];$('#capabilityGrid').innerHTML=caps.map(([name,on])=>`<article class="empire-card"><header><h3>${esc(name)}</h3><span class="status-dot ${on?'live':''}"></span></header><div class="power">${on?'Available':'Not materialized'}</div></article>`).join('');$('#proofCard').innerHTML=`<div><span class="eyebrow">PUBLIC EVIDENCE</span><h3>${esc(e.projection_schema||'unknown')}</h3></div><div class="proof-grid"><span>Manifest</span><code>${esc(e.manifest_hash||'—')}</code><span>World</span><code>${esc(e.world_hash||'—')}</code><span>Event head</span><code>${esc(e.event_head_hash||'none')}</code><span>State hash</span><code>${esc(e.state_after_hash||'none')}</code></div><p class="muted">${esc(e.claim||'')}</p>`}
function renderIdentity(){if(!state)return;$('#viewerDid').value=viewerDid;const m=membership(),emp=myEmpire();$('#identityStatus').innerHTML=viewerDid?(m?`<strong>${esc(emp.name)}</strong><br><span class="muted">${esc(viewerDid)} · member of ${esc(m.empire_id)}</span>`:`<strong>DID saved locally</strong><br><span class="muted">No empire membership is visible for this DID. Register first if needed, then join one Season 0 empire.</span>`):'<strong>Observer mode</strong><br><span class="muted">Set your DID to highlight your empire and prefill signed commands.</span>';$('#claimGrid').innerHTML=state.world.empires.map(e=>`<button class="claim-btn" data-join="${e.id}" ${m?'disabled':''}><span><strong>${esc(e.name)}</strong><small class="muted">${e.members} member${e.members===1?'':'s'}</small></span><i style="background:${e.color}"></i></button>`).join('');$$('[data-join]').forEach(b=>b.onclick=()=>openJoin(b.dataset.join))}
function openSheet(id){$$('.command-sheet').forEach(s=>{const on=s.id===id;s.classList.toggle('open',on);s.setAttribute('aria-hidden',String(!on))})}
function closeSheets(){$$('.command-sheet').forEach(s=>{s.classList.remove('open');s.setAttribute('aria-hidden','true')})}
function didOrPlaceholder(){return viewerDid||'YOUR_DID'}
function uid(prefix){return `season0-${prefix}-YOUR_UNIQUE_ID`}
function setCommand(title,hint,obj,fields=''){const text=canonical(obj);$('#commandTitle').textContent=title;$('#commandHint').textContent=hint;$('#commandForm').innerHTML=fields;$('#commandPreview').textContent=text;$('#commandSheet').dataset.command=text;openSheet('commandSheet')}
function syncPreview(builder){const update=()=>{const obj=builder();const text=canonical(obj);$('#commandPreview').textContent=text;$('#commandSheet').dataset.command=text};$$('#commandForm input,#commandForm select').forEach(el=>el.addEventListener('input',update));update()}
function openRegister(){const obj={action:'register_actor',actor_did:didOrPlaceholder(),payload:{},request_id:uid('register')};setCommand('Register actor','Sign and post this canonical command in the Season 0 actions room.',obj)}
function openJoin(empireId){const did=didOrPlaceholder();const fields=`<label class="field wide"><span>Empire</span><input id="fEmpire" value="${esc(empireId)}" readonly /></label>`;setCommand('Join empire','If this DID is not registered yet, register it first. Joining freezes one membership for this actor.',{action:'join_empire',actor_did:did,payload:{empire_id:empireId},request_id:uid('join')},fields);syncPreview(()=>({action:'join_empire',actor_did:did,payload:{empire_id:$('#fEmpire').value},request_id:uid('join')}))}
function openAction(kind,t){const did=didOrPlaceholder(),mine=myEmpire()?.id||null;if(kind==='recon'){setCommand('Recon territory','Recon is a signed active-season command; returned intel expires under the frozen rule window.',{action:'recon',actor_did:did,payload:{territory_id:t.id},request_id:uid('recon')});return}if(kind==='fortify'){const fields='<label class="field wide"><span>Engineering amount</span><input id="fAmount" type="number" min="1" value="12" /></label>';setCommand('Fortify territory','Spend unlocked Engineering to raise fortification on a territory your empire owns.',{},fields);syncPreview(()=>({action:'fortify',actor_did:did,payload:{territory_id:t.id,amount:Number($('#fAmount').value||0)},request_id:uid('fortify')}));return}const origins=neighbors(t.id).map(id=>state.world.territories.find(x=>x.id===id)).filter(x=>x&&mine&&x.owner===mine);const isSiege=kind==='siege',min=isSiege?24:14,windowSec=isSiege?21600:1800;const opts=origins.length?origins.map(o=>`<option value="${o.id}">${o.id}</option>`).join(''):'<option value="YOUR_ADJACENT_TERRITORY">No owned adjacent territory detected</option>';const fields=`<label class="field"><span>Origin</span><select id="fOrigin">${opts}</select></label><label class="field"><span>Power</span><input id="fPower" type="number" min="${min}" value="${min}" /></label>`;setCommand(`${isSiege?'Siege':'Raid'} territory`,isSiege?'Siege may transfer an adjacent non-capital territory after the frozen defense window.':'Raid cannot transfer territory; it opens the frozen defense window.',{},fields);syncPreview(()=>({action:'create_attack',actor_did:did,payload:{attack_id:uid('attack'),origin_id:$('#fOrigin').value,target_id:t.id,kind:isSiege?'SIEGE':'RAID',power:Number($('#fPower').value||0),deadline_seconds:windowSec},request_id:uid(kind)}))}
function renderIdentity(){if(!state)return;$('#viewerDid').value=viewerDid;const m=membership(),emp=myEmpire();$('#identityStatus').innerHTML=viewerDid?(m?`<strong>${esc(emp.name)}</strong><br><span class="muted">${esc(viewerDid)} · member of ${esc(m.empire_id)}</span>`:`<strong>DID saved locally</strong><br><span class="muted">No empire membership is visible for this DID.</span><br><button class="action-btn" id="registerActor">Build register command</button>`):'<strong>Observer mode</strong><br><span class="muted">Set your DID to highlight your empire and prefill signed commands.</span>';$('#claimGrid').innerHTML=state.world.empires.map(e=>`<button class="claim-btn" data-join="${e.id}" ${m?'disabled':''}><span><strong>${esc(e.name)}</strong><small class="muted">${e.members} member${e.members===1?'':'s'}</small></span><i style="background:${e.color}"></i></button>`).join('');$$('[data-join]').forEach(b=>b.onclick=()=>openJoin(b.dataset.join));const reg=$('#registerActor');if(reg)reg.onclick=openRegister}
function zoom(factor,cx=view.x+view.w/2,cy=view.y+view.h/2){const nw=Math.max(260,Math.min(900,view.w*factor)),nh=nw;const rx=(cx-view.x)/view.w,ry=(cy-view.y)/view.h;view={x:cx-rx*nw,y:cy-ry*nh,w:nw,h:nh};renderMap()}
function resetView(){view={x:0,y:0,w:900,h:900};renderMap()}
function pointerToWorld(e){const svg=$('#worldMap'),r=svg.getBoundingClientRect();return {x:view.x+(e.clientX-r.left)/r.width*view.w,y:view.y+(e.clientY-r.top)/r.height*view.h}}
const svg=$('#worldMap');svg.addEventListener('wheel',e=>{e.preventDefault();const p=pointerToWorld(e);zoom(e.deltaY>0?1.12:.88,p.x,p.y)},{passive:false});svg.addEventListener('pointerdown',e=>{drag={id:e.pointerId,startX:e.clientX,startY:e.clientY,baseX:view.x,baseY:view.y};svg.setPointerCapture(e.pointerId);svg.classList.add('dragging')});svg.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const r=svg.getBoundingClientRect();view.x=drag.baseX-(e.clientX-drag.startX)/r.width*view.w;view.y=drag.baseY-(e.clientY-drag.startY)/r.height*view.h;svg.setAttribute('viewBox',`${view.x} ${view.y} ${view.w} ${view.h}`)});svg.addEventListener('pointerup',e=>{if(drag&&drag.id===e.pointerId){drag=null;svg.classList.remove('dragging')}});svg.addEventListener('pointercancel',()=>{drag=null;svg.classList.remove('dragging')});
$$('.tab').forEach(btn=>btn.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===btn));$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===btn.dataset.tab))}));
$$('[data-close-sheet]').forEach(b=>b.addEventListener('click',closeSheets));
$('#identityButton').addEventListener('click',()=>openSheet('identitySheet'));
$('#viewerDid').addEventListener('change',e=>{viewerDid=e.target.value.trim();if(viewerDid)localStorage.setItem('flopEmpiresViewerDid',viewerDid);else localStorage.removeItem('flopEmpiresViewerDid');render();toast(viewerDid?'Identity saved locally':'Observer mode')});
$('#copyCommand').addEventListener('click',async()=>{const text=$('#commandSheet').dataset.command||'';try{await navigator.clipboard.writeText(text);toast('Canonical JSON copied')}catch{toast('Copy unavailable')}});
$('#zoomIn').addEventListener('click',()=>zoom(.8));$('#zoomOut').addEventListener('click',()=>zoom(1.25));$('#resetView').addEventListener('click',resetView);
$$('.filter').forEach(b=>b.addEventListener('click',()=>{layer=b.dataset.layer;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));renderMap()}));
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeSheets()});
load();refreshTimer=setInterval(load,10000);
