const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
let state=null,selected=null,refreshTimer=null;
const fmt=n=>new Intl.NumberFormat('en-US').format(Number(n||0));
const time=t=>new Date(Number(t)*1000).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function canonical(obj){const sort=x=>Array.isArray(x)?x.map(sort):x&&typeof x==='object'?Object.fromEntries(Object.keys(x).sort().map(k=>[k,sort(x[k])])):x;return JSON.stringify(sort(obj))}
async function load(){try{const r=await fetch('/api/state',{cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);state=await r.json();render()}catch(e){$('#statusText').textContent='UI offline';console.error(e)}}
function render(){renderHeader();renderStats();renderMap();renderEmpires();renderWar();renderActivity();renderRules();if(selected)renderTerritory(selected)}
function renderHeader(){const s=state.season,now=Date.now()/1000;$('#statusText').textContent=s.status;$('#statusDot').classList.toggle('live',['REGISTRATION','ACTIVE'].includes(s.status));let label='';if(s.status==='REGISTRATION')label=` · starts ${time(s.season_start)}`;else if(s.status==='ACTIVE')label=` · ends ${time(s.season_end)}`;$('#countdown').textContent=label;document.title=`FLOP Empires · ${s.status}`}
function renderStats(){const s=state,w=state.world,a=state.activity,claimed=w.empires.filter(e=>e.claimed).length;const cards=[['Phase',s.status,`Season 0 · ${time(s.season_start)}`],['Registered',state.registration.actors,`${claimed}/16 empire slots claimed`],['World','64 territories',w.live_materialized?'Live materialized':'Frozen baseline'],['Open attacks',a.active_attacks.length,`${a.active_alliances.length} active alliances`]];$('#heroStats').innerHTML=cards.map(([k,v,x])=>`<div class="stat"><span>${esc(k)}</span><strong>${esc(v)}</strong><small>${esc(x)}</small></div>`).join('')}
function renderMap(){const svg=$('#worldMap'),byId=Object.fromEntries(state.world.territories.map(t=>[t.id,t]));let out='';for(const [a,b] of state.world.edges){const A=byId[a],B=byId[b];if(A&&B)out+=`<line class="edge" x1="${A.x}" y1="${A.y}" x2="${B.x}" y2="${B.y}"/>`}
for(const atk of state.activity.active_attacks){const A=byId[atk.origin_id],B=byId[atk.target_id];if(A&&B)out+=`<line class="attack-line" x1="${A.x}" y1="${A.y}" x2="${B.x}" y2="${B.y}"/>`}
for(const t of state.world.territories){const cls=selected===t.id?'territory selected':'territory';const r=t.capital?16:t.strategic_value>1?13:10;out+=`<g class="${cls}" data-id="${t.id}" tabindex="0" role="button" aria-label="${esc(t.id)} owned by ${esc(t.owner_name)}"><circle class="node" cx="${t.x}" cy="${t.y}" r="${r}" fill="${t.color}"/>${t.capital?`<circle class="ring" cx="${t.x}" cy="${t.y}" r="${r+5}"/>`:''}${t.strategic_value>1?`<text x="${t.x}" y="${t.y}">✦</text>`:''}</g>`}
svg.innerHTML=out;$$('.territory',svg).forEach(el=>{const pick=()=>{selected=el.dataset.id;renderMap();renderTerritory(selected)};el.addEventListener('click',pick);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick()}})});$('#worldNotice').textContent=state.world.live_materialized?'Showing live canonical world state.':'Showing the frozen Season 0 baseline; live world rows have not been materialized yet.'}
function neighbors(id){const n=[];for(const [a,b] of state.world.edges){if(a===id)n.push(b);else if(b===id)n.push(a)}return n.sort()}
function renderTerritory(id){const t=state.world.territories.find(x=>x.id===id);if(!t)return;const atk=state.activity.active_attacks.find(a=>a.target_id===id||a.origin_id===id);$('#territoryDetail').innerHTML=`<div class="detail-title"><div><span class="eyebrow">${esc(t.region.toUpperCase())}</span><h2>${esc(t.id)}</h2></div><span>${t.capital?'◆ CAPITAL':t.strategic_value>1?'✦ STRATEGIC':''}</span></div><div class="owner-pill"><i style="background:${t.color}"></i>${esc(t.owner_name)}</div><div class="kv"><div><span>Strategic value</span><strong>${fmt(t.strategic_value)}</strong></div><div><span>Fortification</span><strong>Hidden by fog</strong></div><div><span>Production</span><strong>Hidden by fog</strong></div><div><span>State</span><strong>${t.live?'Canonical live':'Frozen baseline'}</strong></div></div><div class="neighbors">${neighbors(id).map(n=>`<button class="chip" data-neighbor="${n}">${n}</button>`).join('')}</div>${atk?`<div class="world-notice">Open ${esc(atk.kind)} · deadline ${time(atk.deadline_at)}</div>`:''}<div class="detail-actions"><button class="action-btn" data-action="recon">Recon</button><button class="action-btn" data-action="attack">Attack</button></div>`;$$('[data-neighbor]').forEach(b=>b.onclick=()=>{selected=b.dataset.neighbor;renderMap();renderTerritory(selected)});$$('[data-action]').forEach(b=>b.onclick=()=>openCommand(b.dataset.action,t))}
function renderEmpires(){const sorted=[...state.world.empires].sort((a,b)=>Number(b.claimed)-Number(a.claimed)||a.id.localeCompare(b.id));$('#empireGrid').innerHTML=sorted.map(e=>`<article class="empire-card ${e.claimed?'':'unclaimed'}"><header><h3>${esc(e.name)}</h3><span class="swatch" style="background:${e.color}"></span></header><div class="power">${esc(e.standing||'Unranked')}</div><small class="muted">Standing · ${e.claimed?`${e.members} member${e.members===1?'':'s'}`:'unclaimed slot'}</small><div class="resource-row"><div><small>PRESTIGE</small><strong>${fmt(e.prestige_public)}</strong></div><div><small>FOG</small><strong>ON</strong></div><div><small>STATE</small><strong>${e.standing?'LIVE':'PENDING'}</strong></div></div></article>`).join('')}
function renderWar(){const list=state.activity.active_attacks;if(!list.length){$('#warList').innerHTML='<div class="empty-state">No open Raid or Siege windows.</div>';return}$('#warList').innerHTML=list.map(a=>`<article class="list-item"><div class="event-icon">${a.kind==='SIEGE'?'S':'R'}</div><div><strong>${esc(a.attacker_empire_id)} → ${esc(a.defender_empire_id)}</strong><small>${esc(a.origin_id)} → ${esc(a.target_id)} · committed force hidden by fog</small></div><time>${time(a.deadline_at)}</time></article>`).join('')}
function renderActivity(){const list=state.activity.recent_events;if(!list.length){$('#activityList').innerHTML='<div class="empty-state">No canonical game events yet.</div>';return}$('#activityList').innerHTML=list.map(e=>`<article class="list-item"><div class="event-icon">${e.accepted?'✓':'×'}</div><div><strong>${esc(e.event_type)}</strong><small>${esc(e.request_id)} · event #${fmt(e.seq)}</small></div><time>${time(e.accepted_at)}</time></article>`).join('')}
function renderRules(){const c=state.capabilities||{},e=state.evidence||{};const caps=[['Fog-safe projection',c.fog_safe_public_projection],['Raid / Siege',c.raid_siege],['Recon',c.recon],['Alliances runtime',c.alliances_runtime],['Treaties rule contract',c.treaties_rule_contract],['Treaties runtime',c.treaties_runtime_materialized],['Trade rule contract',c.trade_rule_contract],['Trade runtime',c.trade_runtime_materialized],['Standing runtime',c.standing_runtime_materialized]];$('#capabilityGrid').innerHTML=caps.map(([name,on])=>`<article class="empire-card"><header><h3>${esc(name)}</h3><span class="status-dot ${on?'live':''}"></span></header><div class="power">${on?'Available':'Not materialized'}</div></article>`).join('');$('#proofCard').innerHTML=`<div><span class="eyebrow">PUBLIC EVIDENCE</span><h3>${esc(e.projection_schema||'unknown')}</h3></div><div class="proof-grid"><span>Manifest</span><code>${esc(e.manifest_hash||'—')}</code><span>World</span><code>${esc(e.world_hash||'—')}</code><span>Event head</span><code>${esc(e.event_head_hash||'none')}</code><span>State hash</span><code>${esc(e.state_after_hash||'none')}</code></div><p class="muted">${esc(e.claim||'')}</p>`}
function openCommand(kind,t){let payload,action=kind;if(kind==='recon')payload={territory_id:t.id};else{action='create_attack';payload={attack_id:'season0-attack-YOUR_UNIQUE_ID',origin_id:'YOUR_ADJACENT_TERRITORY',target_id:t.id,kind:'RAID',power:14,deadline_seconds:1800}}const obj={action,actor_did:'YOUR_DID',payload,request_id:`season0-${kind}-YOUR_UNIQUE_ID`};const text=canonical(obj);$('#commandPreview').textContent=text;$('#commandHint').textContent='Sign and post this canonical command through the Season 0 actions room. Replace YOUR_* fields before signing.';$('#commandSheet').dataset.command=text;$('#commandSheet').classList.add('open');$('#commandSheet').setAttribute('aria-hidden','false')}
function closeSheet(){$('#commandSheet').classList.remove('open');$('#commandSheet').setAttribute('aria-hidden','true')}
$$('.tab').forEach(btn=>btn.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.toggle('active',x===btn));$$('.tab-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===btn.dataset.tab))}));
$('#closeSheet').addEventListener('click',closeSheet);$('#copyCommand').addEventListener('click',async()=>{const text=$('#commandSheet').dataset.command||'';try{await navigator.clipboard.writeText(text);toast('Canonical JSON copied')}catch{toast('Copy unavailable')}});
window.addEventListener('keydown',e=>{if(e.key==='Escape')closeSheet()});
load();refreshTimer=setInterval(load,10000);
